### ISSUE TITLE
CCF - Keycloak IDP Integration - FE

### ISSUE THREAD

**Issue by rashidtruba** [appnetwise/cloud-carbon-footprint#36]
Below are the task completed
1 ) Login with Keycloak
2 ) Logout with Keycloak
3 ) User creation for both Microsoft and Direct user
4 ) Get User Profile for both cases

In Progress :
Connect to Cloud

**Comment by rashidtruba** [comment]
Below are the task completed
1 ) Login  with Keycloak
2 ) Logout  with Keycloak
3 ) User creation for both Microsoft and Direct user
4 ) Get User Profile for both cases

In Progress :
Connect to Cloud

**Comment by rashid-anw** [comment]
dev completed now
